//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id_Product { get; set; }
        public string Name_Product { get; set; }
        public string PriceProduct { get; set; }
        public string PicProduct { get; set; }
    }
}
